spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/usercenter_db
      username: root
      password: xiaoooooobawang
  # session 失效时间
  session:
    timeout: 86400

