spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/usercenter_db
      username: root
      password: xiaoooooobawang
  # session 失效时间
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api

# 可不在这里设置，在逻辑删除字段前@TableLogic(value = "0", delval = "1")设置更简单
# 但在这里设置是全局设置，如果有多个表都有deleted逻辑删除，就不需要一个个加注解
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
